// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = "play" | "pause" | "playPause" | "next" | "previous" | "stop" | "quit" | { "skipTo": { num: number, } } | "jumpForward" | "jumpBackward" | { "playAlbum": { album_id: string, } } | { "playTrack": { track_id: number, } } | { "playUri": { uri: string, } } | { "playPlaylist": { playlist_id: bigint, } } | { "search": { query: string, } } | { "fetchArtistAlbums": { artist_id: number, } } | { "fetchPlaylistTracks": { playlist_id: bigint, } } | "fetchUserPlaylists";
