// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artist } from "./Artist";
import type { Track } from "./Track";

export type Album = { id: string, title: string, artist: Artist, releaseYear: number, hiresAvailable: boolean, explicit: boolean, totalTracks: number, tracks: { [key in number]?: Track }, available: boolean, coverArt: string, coverArtSmall: string, };
