// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";

export type Artist = { id: number, name: string, albums: Array<Album> | null, };
