// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

export type Playlist = { title: string, durationSeconds: number, tracksCount: number, id: number, coverArt: string | null, tracks: { [key in number]?: Track }, };
