// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";
import type { Artist } from "./Artist";
import type { Playlist } from "./Playlist";
import type { Track } from "./Track";

export type SearchResults = { query: string, albums: Array<Album>, tracks: Array<Track>, artists: Array<Artist>, playlists: Array<Playlist>, };
