// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";
import type { Playlist } from "./Playlist";
import type { Track } from "./Track";
import type { TrackListType } from "./TrackListType";

/**
 * A tracklist is a list of tracks.
 */
export type TrackListValue = { queue: Array<Track>, album: Album | null, playlist: Playlist | null, list_type: TrackListType, };
